server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    servlet:
        context-path: /producer

spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    freemarker:
      suffix: .html

    rabbitmq:
      virtual-host: /
      username: guest
      password: guest
      publisher-confirms: true
      port: 5672
      host: 192.168.244.128
      publisher-returns: true











#rabbitmq:
#  ip: 192.168.244.128
#  port: 5672
#  username: guest
#  password: guest
#  virtualHost: /
#  concurrentConsumers: 3
#  maxConcurrentConsumers: 10
